### PR TITLE
Fix Join Cards layout when screen size changes

### LINKED ISSUE #8: Join Card
- src\components\JoinCard.jsx
image
hover:
image

### PR DESCRIPTION
**Pull request by suhanic44**
Screen Shot 2023-07-12 at 2 28 05 PM

* Buttons wrap instead of decrease in size when screen size is decreased

### CODE REVIEW

File: src/components/JoinCard.jsx [hunk 1]
```diff
@@ -3,10 +3,10 @@ import { FaEnvelope, FaLink, FaFacebook, FaInstagram } from "react-icons/fa6";
 
 const JoinCard = () => {
   return (
-    <div className="flex flex-wrap" style={{ justifyContent: "left" }}>
+    <div className="flex flex-wrap" style={{ justifyContent: "center" }}>
```
Comment (menthy-wu) [inline src/components/JoinCard.jsx]: use tailiwnd instead of style

File: src/components/JoinCard.jsx [hunk 2]
```diff
@@ -3,10 +3,10 @@ import { FaEnvelope, FaLink, FaFacebook, FaInstagram } from "react-icons/fa6";
...
       <div
         className="flex flex-col bg-asme-blue-600"
-        style={{ margin: "3.5%", width: "18%" }}
+        style={{ margin: "30px", width: "230px", height: "230px" }}
```
Comment (menthy-wu) [inline src/components/JoinCard.jsx]: you can add in className "m-[30px] w-[230px] h-[230px]"

**Review by menthy-wu — CHANGES_REQUESTED** [review]

File: src/components/JoinCard.jsx [hunk 3]
```diff
@@ -26,17 +23,14 @@ const JoinCard = () => {
           >
             <button
               className=" bg-asme-blue-600 border pt-1 pb-1 pl-4 pr-4 outline-white hover:bg-white hover:text-asme-blue-600 font-poppins font-semibold"
-              style={{ width: "40%", margin: "5%" }}
+              style={{ margin: "5%", width: "40%" }}
```
Comment (menthy-wu) [inline src/components/JoinCard.jsx]: use tailwind

File: src/components/JoinCard.jsx [hunk 4]
```diff
@@ -57,18 +51,15 @@ const JoinCard = () => {
           >
             <button
               className="bg-asme-blue-500 border pt-1 pb-1 pl-4 pr-4 outline-white hover:bg-white hover:text-asme-blue-500 font-poppins font-semibold"
-              style={{ width: "40%", margin: "5%" }}
+              style={{ margin: "5%", width: "40%" }}
```
Comment (menthy-wu) [inline src/components/JoinCard.jsx]: use tailwind

File: src/components/JoinCard.jsx [hunk 5]
```diff
@@ -87,18 +78,15 @@ const JoinCard = () => {
           >
             <button
               className="bg-asme-blue-400 border pt-1 pb-1 pl-4 pr-4 outline-white hover:bg-white hover:text-asme-blue-400 font-poppins font-semibold"
-              style={{ width: "40%", margin: "5%" }}
+              style={{ margin: "5%", width: "40%" }}
```
Comment (menthy-wu) [inline src/components/JoinCard.jsx]: use tailwind

File: src/components/JoinCard.jsx [hunk 6]
```diff
@@ -117,7 +105,7 @@ const JoinCard = () => {
           >
             <button
               className="bg-asme-blue-200 border pt-1 pb-1 pl-4 pr-4 outline-white hover:bg-white hover:text-asme-blue-200 font-poppins font-semibold"
-              style={{ width: "40%", margin: "5%" }}
+              style={{ margin: "5%", width: "40%" }}
```
Comment (menthy-wu) [inline src/components/JoinCard.jsx]: use tailwind

**Review by menthy-wu — CHANGES_REQUESTED** [review]

**Review by menthy-wu — APPROVED** [review]
